[package]
name = "compiling"
version = "0.1.0"
edition = "2021"

[dependencies]
# cortex-m-rt = { version = "0.7.3", features = ["device"] }
# cortex-m-rt = "0.7.3"
panic-halt = "0.2.0"
# microbit-v2 = "0.13.0"

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'
